services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
    networks:
      - pg-networks

  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "8080:80"
    networks:
      - pg-networks

networks:
  pg-networks:
    driver: bridge

  # taxi_ingest:
  #   image: taxi_ingest:v001
  #   command:
  #     - "--user=root"
  #     - "--password=root"
  #     - "--host=pgdatabase"
  #     - "--port=5432"
  #     - "--db=ny_taxi"
  #     - "--table_name=yellow_taxi_trips"
  #     - "--url=https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2023-10.parquet"
  #   depends_on:
  #     - pgdatabases